//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("iBooxModel", "Books_Covers", "Cover", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(iBoox.Models.Cover), "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(iBoox.Models.Book), true)]
[assembly: EdmRelationshipAttribute("iBooxModel", "Books_Publishers", "Publisher", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(iBoox.Models.Publisher), "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(iBoox.Models.Book), true)]
[assembly: EdmRelationshipAttribute("iBooxModel", "Books_Series", "Series", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(iBoox.Models.Series), "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(iBoox.Models.Book), true)]
[assembly: EdmRelationshipAttribute("iBooxModel", "Books_Themes", "Theme", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(iBoox.Models.Theme), "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(iBoox.Models.Book), true)]
[assembly: EdmRelationshipAttribute("iBooxModel", "BooksAuthors", "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(iBoox.Models.Book), "Author", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(iBoox.Models.Author))]
[assembly: EdmRelationshipAttribute("iBooxModel", "Books_Comments", "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(iBoox.Models.Book), "BookComment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(iBoox.Models.BookComment), true)]
[assembly: EdmRelationshipAttribute("iBooxModel", "Books_Votes", "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(iBoox.Models.Book), "BookVote", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(iBoox.Models.BookVote), true)]

#endregion

namespace iBoox.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class iBooxEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new iBooxEntities object using the connection string found in the 'iBooxEntities' section of the application configuration file.
        /// </summary>
        public iBooxEntities() : base("name=iBooxEntities", "iBooxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new iBooxEntities object.
        /// </summary>
        public iBooxEntities(string connectionString) : base(connectionString, "iBooxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new iBooxEntities object.
        /// </summary>
        public iBooxEntities(EntityConnection connection) : base(connection, "iBooxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Author> Authors
        {
            get
            {
                if ((_Authors == null))
                {
                    _Authors = base.CreateObjectSet<Author>("Authors");
                }
                return _Authors;
            }
        }
        private ObjectSet<Author> _Authors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Publisher> Publishers
        {
            get
            {
                if ((_Publishers == null))
                {
                    _Publishers = base.CreateObjectSet<Publisher>("Publishers");
                }
                return _Publishers;
            }
        }
        private ObjectSet<Publisher> _Publishers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Series> Series
        {
            get
            {
                if ((_Series == null))
                {
                    _Series = base.CreateObjectSet<Series>("Series");
                }
                return _Series;
            }
        }
        private ObjectSet<Series> _Series;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Theme> Themes
        {
            get
            {
                if ((_Themes == null))
                {
                    _Themes = base.CreateObjectSet<Theme>("Themes");
                }
                return _Themes;
            }
        }
        private ObjectSet<Theme> _Themes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Book> Books
        {
            get
            {
                if ((_Books == null))
                {
                    _Books = base.CreateObjectSet<Book>("Books");
                }
                return _Books;
            }
        }
        private ObjectSet<Book> _Books;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cover> Covers
        {
            get
            {
                if ((_Covers == null))
                {
                    _Covers = base.CreateObjectSet<Cover>("Covers");
                }
                return _Covers;
            }
        }
        private ObjectSet<Cover> _Covers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tag> Tags
        {
            get
            {
                if ((_Tags == null))
                {
                    _Tags = base.CreateObjectSet<Tag>("Tags");
                }
                return _Tags;
            }
        }
        private ObjectSet<Tag> _Tags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BookComment> BookComments
        {
            get
            {
                if ((_BookComments == null))
                {
                    _BookComments = base.CreateObjectSet<BookComment>("BookComments");
                }
                return _BookComments;
            }
        }
        private ObjectSet<BookComment> _BookComments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BookVote> BookVotes
        {
            get
            {
                if ((_BookVotes == null))
                {
                    _BookVotes = base.CreateObjectSet<BookVote>("BookVotes");
                }
                return _BookVotes;
            }
        }
        private ObjectSet<BookVote> _BookVotes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Authors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuthors(Author author)
        {
            base.AddObject("Authors", author);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Publishers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPublishers(Publisher publisher)
        {
            base.AddObject("Publishers", publisher);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Series EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeries(Series series)
        {
            base.AddObject("Series", series);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Themes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToThemes(Theme theme)
        {
            base.AddObject("Themes", theme);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Books EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBooks(Book book)
        {
            base.AddObject("Books", book);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Covers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCovers(Cover cover)
        {
            base.AddObject("Covers", cover);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTags(Tag tag)
        {
            base.AddObject("Tags", tag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BookComments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBookComments(BookComment bookComment)
        {
            base.AddObject("BookComments", bookComment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BookVotes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBookVotes(BookVote bookVote)
        {
            base.AddObject("BookVotes", bookVote);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<Series> GetSeriesList()
        {
            return base.ExecuteFunction<Series>("GetSeriesList");
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        public ObjectResult<Series> GetSeriesList(MergeOption mergeOption)
        {
            return base.ExecuteFunction<Series>("GetSeriesList", mergeOption);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<Theme> GetThemesList()
        {
            return base.ExecuteFunction<Theme>("GetThemesList");
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        public ObjectResult<Theme> GetThemesList(MergeOption mergeOption)
        {
            return base.ExecuteFunction<Theme>("GetThemesList", mergeOption);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<Author> GetAuthorsList()
        {
            return base.ExecuteFunction<Author>("GetAuthorsList");
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        public ObjectResult<Author> GetAuthorsList(MergeOption mergeOption)
        {
            return base.ExecuteFunction<Author>("GetAuthorsList", mergeOption);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<global::System.String> GetTagsList()
        {
            return base.ExecuteFunction<global::System.String>("GetTagsList");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="tagID">No Metadata Documentation available.</param>
        public int GetTag(Nullable<global::System.Int32> tagID)
        {
            ObjectParameter tagIDParameter;
            if (tagID.HasValue)
            {
                tagIDParameter = new ObjectParameter("TagID", tagID);
            }
            else
            {
                tagIDParameter = new ObjectParameter("TagID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("GetTag", tagIDParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="iBooxModel", Name="Author")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Author : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Author object.
        /// </summary>
        /// <param name="authorID">Initial value of the AuthorID property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        public static Author CreateAuthor(global::System.Int32 authorID, global::System.String lastName, global::System.String firstName)
        {
            Author author = new Author();
            author.AuthorID = authorID;
            author.LastName = lastName;
            author.FirstName = firstName;
            return author;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AuthorID
        {
            get
            {
                return _AuthorID;
            }
            set
            {
                if (_AuthorID != value)
                {
                    OnAuthorIDChanging(value);
                    ReportPropertyChanging("AuthorID");
                    _AuthorID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AuthorID");
                    OnAuthorIDChanged();
                }
            }
        }
        private global::System.Int32 _AuthorID;
        partial void OnAuthorIDChanging(global::System.Int32 value);
        partial void OnAuthorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIO
        {
            get
            {
                return _FIO;
            }
            set
            {
                OnFIOChanging(value);
                ReportPropertyChanging("FIO");
                _FIO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIO");
                OnFIOChanged();
            }
        }
        private global::System.String _FIO;
        partial void OnFIOChanging(global::System.String value);
        partial void OnFIOChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iBooxModel", "BooksAuthors", "Book")]
        public EntityCollection<Book> Books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Book>("iBooxModel.BooksAuthors", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Book>("iBooxModel.BooksAuthors", "Book", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="iBooxModel", Name="Book")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Book : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Book object.
        /// </summary>
        /// <param name="bookID">Initial value of the BookID property.</param>
        /// <param name="iSBN">Initial value of the ISBN property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="seriesID">Initial value of the SeriesID property.</param>
        /// <param name="pages">Initial value of the Pages property.</param>
        /// <param name="publicationYear">Initial value of the PublicationYear property.</param>
        /// <param name="size">Initial value of the Size property.</param>
        /// <param name="coverID">Initial value of the CoverID property.</param>
        /// <param name="cover2">Initial value of the Cover2 property.</param>
        /// <param name="themeID">Initial value of the ThemeID property.</param>
        /// <param name="publisherID">Initial value of the PublisherID property.</param>
        /// <param name="tags">Initial value of the Tags property.</param>
        /// <param name="authorsList">Initial value of the AuthorsList property.</param>
        /// <param name="votes">Initial value of the Votes property.</param>
        /// <param name="totalRating">Initial value of the TotalRating property.</param>
        public static Book CreateBook(global::System.Int32 bookID, global::System.String iSBN, global::System.String title, global::System.String seriesID, global::System.Int16 pages, global::System.Int16 publicationYear, global::System.String size, global::System.String coverID, global::System.Int32 cover2, global::System.String themeID, global::System.Int32 publisherID, global::System.String tags, global::System.String authorsList, global::System.Int32 votes, global::System.Int32 totalRating)
        {
            Book book = new Book();
            book.BookID = bookID;
            book.ISBN = iSBN;
            book.Title = title;
            book.SeriesID = seriesID;
            book.Pages = pages;
            book.PublicationYear = publicationYear;
            book.Size = size;
            book.CoverID = coverID;
            book.Cover2 = cover2;
            book.ThemeID = themeID;
            book.PublisherID = publisherID;
            book.Tags = tags;
            book.AuthorsList = authorsList;
            book.Votes = votes;
            book.TotalRating = totalRating;
            return book;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BookID
        {
            get
            {
                return _BookID;
            }
            set
            {
                if (_BookID != value)
                {
                    OnBookIDChanging(value);
                    ReportPropertyChanging("BookID");
                    _BookID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BookID");
                    OnBookIDChanged();
                }
            }
        }
        private global::System.Int32 _BookID;
        partial void OnBookIDChanging(global::System.Int32 value);
        partial void OnBookIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ISBN
        {
            get
            {
                return _ISBN;
            }
            set
            {
                OnISBNChanging(value);
                ReportPropertyChanging("ISBN");
                _ISBN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ISBN");
                OnISBNChanged();
            }
        }
        private global::System.String _ISBN;
        partial void OnISBNChanging(global::System.String value);
        partial void OnISBNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SeriesID
        {
            get
            {
                return _SeriesID;
            }
            set
            {
                OnSeriesIDChanging(value);
                ReportPropertyChanging("SeriesID");
                _SeriesID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SeriesID");
                OnSeriesIDChanged();
            }
        }
        private global::System.String _SeriesID;
        partial void OnSeriesIDChanging(global::System.String value);
        partial void OnSeriesIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Pages
        {
            get
            {
                return _Pages;
            }
            set
            {
                OnPagesChanging(value);
                ReportPropertyChanging("Pages");
                _Pages = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pages");
                OnPagesChanged();
            }
        }
        private global::System.Int16 _Pages;
        partial void OnPagesChanging(global::System.Int16 value);
        partial void OnPagesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 PublicationYear
        {
            get
            {
                return _PublicationYear;
            }
            set
            {
                OnPublicationYearChanging(value);
                ReportPropertyChanging("PublicationYear");
                _PublicationYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PublicationYear");
                OnPublicationYearChanged();
            }
        }
        private global::System.Int16 _PublicationYear;
        partial void OnPublicationYearChanging(global::System.Int16 value);
        partial void OnPublicationYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private global::System.String _Size;
        partial void OnSizeChanging(global::System.String value);
        partial void OnSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CoverID
        {
            get
            {
                return _CoverID;
            }
            set
            {
                OnCoverIDChanging(value);
                ReportPropertyChanging("CoverID");
                _CoverID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CoverID");
                OnCoverIDChanged();
            }
        }
        private global::System.String _CoverID;
        partial void OnCoverIDChanging(global::System.String value);
        partial void OnCoverIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cover2
        {
            get
            {
                return _Cover2;
            }
            set
            {
                OnCover2Changing(value);
                ReportPropertyChanging("Cover2");
                _Cover2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cover2");
                OnCover2Changed();
            }
        }
        private global::System.Int32 _Cover2;
        partial void OnCover2Changing(global::System.Int32 value);
        partial void OnCover2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ThemeID
        {
            get
            {
                return _ThemeID;
            }
            set
            {
                OnThemeIDChanging(value);
                ReportPropertyChanging("ThemeID");
                _ThemeID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ThemeID");
                OnThemeIDChanged();
            }
        }
        private global::System.String _ThemeID;
        partial void OnThemeIDChanging(global::System.String value);
        partial void OnThemeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Annotation
        {
            get
            {
                return _Annotation;
            }
            set
            {
                OnAnnotationChanging(value);
                ReportPropertyChanging("Annotation");
                _Annotation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Annotation");
                OnAnnotationChanged();
            }
        }
        private global::System.String _Annotation;
        partial void OnAnnotationChanging(global::System.String value);
        partial void OnAnnotationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PublisherID
        {
            get
            {
                return _PublisherID;
            }
            set
            {
                OnPublisherIDChanging(value);
                ReportPropertyChanging("PublisherID");
                _PublisherID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PublisherID");
                OnPublisherIDChanged();
            }
        }
        private global::System.Int32 _PublisherID;
        partial void OnPublisherIDChanging(global::System.Int32 value);
        partial void OnPublisherIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tags
        {
            get
            {
                return _Tags;
            }
            set
            {
                OnTagsChanging(value);
                ReportPropertyChanging("Tags");
                _Tags = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tags");
                OnTagsChanged();
            }
        }
        private global::System.String _Tags;
        partial void OnTagsChanging(global::System.String value);
        partial void OnTagsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AuthorsList
        {
            get
            {
                return _AuthorsList;
            }
            set
            {
                OnAuthorsListChanging(value);
                ReportPropertyChanging("AuthorsList");
                _AuthorsList = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AuthorsList");
                OnAuthorsListChanged();
            }
        }
        private global::System.String _AuthorsList;
        partial void OnAuthorsListChanging(global::System.String value);
        partial void OnAuthorsListChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Votes
        {
            get
            {
                return _Votes;
            }
            set
            {
                OnVotesChanging(value);
                ReportPropertyChanging("Votes");
                _Votes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Votes");
                OnVotesChanged();
            }
        }
        private global::System.Int32 _Votes;
        partial void OnVotesChanging(global::System.Int32 value);
        partial void OnVotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TotalRating
        {
            get
            {
                return _TotalRating;
            }
            set
            {
                OnTotalRatingChanging(value);
                ReportPropertyChanging("TotalRating");
                _TotalRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalRating");
                OnTotalRatingChanged();
            }
        }
        private global::System.Int32 _TotalRating;
        partial void OnTotalRatingChanging(global::System.Int32 value);
        partial void OnTotalRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] upsize_ts
        {
            get
            {
                return StructuralObject.GetValidValue(_upsize_ts);
            }
            set
            {
                Onupsize_tsChanging(value);
                ReportPropertyChanging("upsize_ts");
                _upsize_ts = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("upsize_ts");
                Onupsize_tsChanged();
            }
        }
        private global::System.Byte[] _upsize_ts;
        partial void Onupsize_tsChanging(global::System.Byte[] value);
        partial void Onupsize_tsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iBooxModel", "Books_Covers", "Cover")]
        public Cover Cover
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cover>("iBooxModel.Books_Covers", "Cover").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cover>("iBooxModel.Books_Covers", "Cover").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cover> CoverReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cover>("iBooxModel.Books_Covers", "Cover");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cover>("iBooxModel.Books_Covers", "Cover", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iBooxModel", "Books_Publishers", "Publisher")]
        public Publisher Publisher
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Publisher>("iBooxModel.Books_Publishers", "Publisher").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Publisher>("iBooxModel.Books_Publishers", "Publisher").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Publisher> PublisherReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Publisher>("iBooxModel.Books_Publishers", "Publisher");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Publisher>("iBooxModel.Books_Publishers", "Publisher", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iBooxModel", "Books_Series", "Series")]
        public Series Series
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Series>("iBooxModel.Books_Series", "Series").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Series>("iBooxModel.Books_Series", "Series").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Series> SeriesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Series>("iBooxModel.Books_Series", "Series");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Series>("iBooxModel.Books_Series", "Series", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iBooxModel", "Books_Themes", "Theme")]
        public Theme Theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("iBooxModel.Books_Themes", "Theme").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("iBooxModel.Books_Themes", "Theme").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Theme> ThemeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("iBooxModel.Books_Themes", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Theme>("iBooxModel.Books_Themes", "Theme", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iBooxModel", "BooksAuthors", "Author")]
        public EntityCollection<Author> Authors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Author>("iBooxModel.BooksAuthors", "Author");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Author>("iBooxModel.BooksAuthors", "Author", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iBooxModel", "Books_Comments", "BookComment")]
        public EntityCollection<BookComment> BookComments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BookComment>("iBooxModel.Books_Comments", "BookComment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BookComment>("iBooxModel.Books_Comments", "BookComment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iBooxModel", "Books_Votes", "BookVote")]
        public EntityCollection<BookVote> BookVotes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BookVote>("iBooxModel.Books_Votes", "BookVote");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BookVote>("iBooxModel.Books_Votes", "BookVote", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="iBooxModel", Name="BookComment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BookComment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BookComment object.
        /// </summary>
        /// <param name="bookCommentID">Initial value of the BookCommentID property.</param>
        /// <param name="addedDate">Initial value of the AddedDate property.</param>
        /// <param name="addedBy">Initial value of the AddedBy property.</param>
        /// <param name="addedByIP">Initial value of the AddedByIP property.</param>
        /// <param name="bookID">Initial value of the BookID property.</param>
        /// <param name="body">Initial value of the Body property.</param>
        public static BookComment CreateBookComment(global::System.Int32 bookCommentID, global::System.DateTime addedDate, global::System.String addedBy, global::System.String addedByIP, global::System.Int32 bookID, global::System.String body)
        {
            BookComment bookComment = new BookComment();
            bookComment.BookCommentID = bookCommentID;
            bookComment.AddedDate = addedDate;
            bookComment.AddedBy = addedBy;
            bookComment.AddedByIP = addedByIP;
            bookComment.BookID = bookID;
            bookComment.Body = body;
            return bookComment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BookCommentID
        {
            get
            {
                return _BookCommentID;
            }
            set
            {
                if (_BookCommentID != value)
                {
                    OnBookCommentIDChanging(value);
                    ReportPropertyChanging("BookCommentID");
                    _BookCommentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BookCommentID");
                    OnBookCommentIDChanged();
                }
            }
        }
        private global::System.Int32 _BookCommentID;
        partial void OnBookCommentIDChanging(global::System.Int32 value);
        partial void OnBookCommentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddedDate
        {
            get
            {
                return _AddedDate;
            }
            set
            {
                OnAddedDateChanging(value);
                ReportPropertyChanging("AddedDate");
                _AddedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedDate");
                OnAddedDateChanged();
            }
        }
        private global::System.DateTime _AddedDate;
        partial void OnAddedDateChanging(global::System.DateTime value);
        partial void OnAddedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private global::System.String _AddedBy;
        partial void OnAddedByChanging(global::System.String value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedByIP
        {
            get
            {
                return _AddedByIP;
            }
            set
            {
                OnAddedByIPChanging(value);
                ReportPropertyChanging("AddedByIP");
                _AddedByIP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedByIP");
                OnAddedByIPChanged();
            }
        }
        private global::System.String _AddedByIP;
        partial void OnAddedByIPChanging(global::System.String value);
        partial void OnAddedByIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BookID
        {
            get
            {
                return _BookID;
            }
            set
            {
                OnBookIDChanging(value);
                ReportPropertyChanging("BookID");
                _BookID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BookID");
                OnBookIDChanged();
            }
        }
        private global::System.Int32 _BookID;
        partial void OnBookIDChanging(global::System.Int32 value);
        partial void OnBookIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iBooxModel", "Books_Comments", "Book")]
        public Book Book
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Book>("iBooxModel.Books_Comments", "Book").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Book>("iBooxModel.Books_Comments", "Book").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Book> BookReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Book>("iBooxModel.Books_Comments", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Book>("iBooxModel.Books_Comments", "Book", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="iBooxModel", Name="BookVote")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BookVote : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BookVote object.
        /// </summary>
        /// <param name="voteID">Initial value of the VoteID property.</param>
        /// <param name="bookID">Initial value of the BookID property.</param>
        /// <param name="addedByIP">Initial value of the AddedByIP property.</param>
        /// <param name="addedDate">Initial value of the AddedDate property.</param>
        /// <param name="addedVote">Initial value of the AddedVote property.</param>
        public static BookVote CreateBookVote(global::System.Int32 voteID, global::System.Int32 bookID, global::System.String addedByIP, global::System.DateTime addedDate, global::System.Int32 addedVote)
        {
            BookVote bookVote = new BookVote();
            bookVote.VoteID = voteID;
            bookVote.BookID = bookID;
            bookVote.AddedByIP = addedByIP;
            bookVote.AddedDate = addedDate;
            bookVote.AddedVote = addedVote;
            return bookVote;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VoteID
        {
            get
            {
                return _VoteID;
            }
            set
            {
                if (_VoteID != value)
                {
                    OnVoteIDChanging(value);
                    ReportPropertyChanging("VoteID");
                    _VoteID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VoteID");
                    OnVoteIDChanged();
                }
            }
        }
        private global::System.Int32 _VoteID;
        partial void OnVoteIDChanging(global::System.Int32 value);
        partial void OnVoteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BookID
        {
            get
            {
                return _BookID;
            }
            set
            {
                OnBookIDChanging(value);
                ReportPropertyChanging("BookID");
                _BookID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BookID");
                OnBookIDChanged();
            }
        }
        private global::System.Int32 _BookID;
        partial void OnBookIDChanging(global::System.Int32 value);
        partial void OnBookIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private global::System.String _AddedBy;
        partial void OnAddedByChanging(global::System.String value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedByIP
        {
            get
            {
                return _AddedByIP;
            }
            set
            {
                OnAddedByIPChanging(value);
                ReportPropertyChanging("AddedByIP");
                _AddedByIP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedByIP");
                OnAddedByIPChanged();
            }
        }
        private global::System.String _AddedByIP;
        partial void OnAddedByIPChanging(global::System.String value);
        partial void OnAddedByIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddedDate
        {
            get
            {
                return _AddedDate;
            }
            set
            {
                OnAddedDateChanging(value);
                ReportPropertyChanging("AddedDate");
                _AddedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedDate");
                OnAddedDateChanged();
            }
        }
        private global::System.DateTime _AddedDate;
        partial void OnAddedDateChanging(global::System.DateTime value);
        partial void OnAddedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AddedVote
        {
            get
            {
                return _AddedVote;
            }
            set
            {
                OnAddedVoteChanging(value);
                ReportPropertyChanging("AddedVote");
                _AddedVote = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedVote");
                OnAddedVoteChanged();
            }
        }
        private global::System.Int32 _AddedVote;
        partial void OnAddedVoteChanging(global::System.Int32 value);
        partial void OnAddedVoteChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iBooxModel", "Books_Votes", "Book")]
        public Book Book
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Book>("iBooxModel.Books_Votes", "Book").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Book>("iBooxModel.Books_Votes", "Book").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Book> BookReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Book>("iBooxModel.Books_Votes", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Book>("iBooxModel.Books_Votes", "Book", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="iBooxModel", Name="Cover")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cover : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cover object.
        /// </summary>
        /// <param name="coverID">Initial value of the CoverID property.</param>
        /// <param name="coverFull">Initial value of the CoverFull property.</param>
        public static Cover CreateCover(global::System.String coverID, global::System.String coverFull)
        {
            Cover cover = new Cover();
            cover.CoverID = coverID;
            cover.CoverFull = coverFull;
            return cover;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CoverID
        {
            get
            {
                return _CoverID;
            }
            set
            {
                if (_CoverID != value)
                {
                    OnCoverIDChanging(value);
                    ReportPropertyChanging("CoverID");
                    _CoverID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CoverID");
                    OnCoverIDChanged();
                }
            }
        }
        private global::System.String _CoverID;
        partial void OnCoverIDChanging(global::System.String value);
        partial void OnCoverIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CoverFull
        {
            get
            {
                return _CoverFull;
            }
            set
            {
                OnCoverFullChanging(value);
                ReportPropertyChanging("CoverFull");
                _CoverFull = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CoverFull");
                OnCoverFullChanged();
            }
        }
        private global::System.String _CoverFull;
        partial void OnCoverFullChanging(global::System.String value);
        partial void OnCoverFullChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iBooxModel", "Books_Covers", "Book")]
        public EntityCollection<Book> Books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Book>("iBooxModel.Books_Covers", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Book>("iBooxModel.Books_Covers", "Book", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="iBooxModel", Name="Publisher")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Publisher : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Publisher object.
        /// </summary>
        /// <param name="publisherID">Initial value of the PublisherID property.</param>
        public static Publisher CreatePublisher(global::System.Int32 publisherID)
        {
            Publisher publisher = new Publisher();
            publisher.PublisherID = publisherID;
            return publisher;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PublisherID
        {
            get
            {
                return _PublisherID;
            }
            set
            {
                if (_PublisherID != value)
                {
                    OnPublisherIDChanging(value);
                    ReportPropertyChanging("PublisherID");
                    _PublisherID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PublisherID");
                    OnPublisherIDChanged();
                }
            }
        }
        private global::System.Int32 _PublisherID;
        partial void OnPublisherIDChanging(global::System.Int32 value);
        partial void OnPublisherIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Website
        {
            get
            {
                return _Website;
            }
            set
            {
                OnWebsiteChanging(value);
                ReportPropertyChanging("Website");
                _Website = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Website");
                OnWebsiteChanged();
            }
        }
        private global::System.String _Website;
        partial void OnWebsiteChanging(global::System.String value);
        partial void OnWebsiteChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iBooxModel", "Books_Publishers", "Book")]
        public EntityCollection<Book> Books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Book>("iBooxModel.Books_Publishers", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Book>("iBooxModel.Books_Publishers", "Book", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="iBooxModel", Name="Series")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Series : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Series object.
        /// </summary>
        /// <param name="seriesID">Initial value of the SeriesID property.</param>
        /// <param name="seriesFull">Initial value of the SeriesFull property.</param>
        public static Series CreateSeries(global::System.String seriesID, global::System.String seriesFull)
        {
            Series series = new Series();
            series.SeriesID = seriesID;
            series.SeriesFull = seriesFull;
            return series;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SeriesID
        {
            get
            {
                return _SeriesID;
            }
            set
            {
                if (_SeriesID != value)
                {
                    OnSeriesIDChanging(value);
                    ReportPropertyChanging("SeriesID");
                    _SeriesID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SeriesID");
                    OnSeriesIDChanged();
                }
            }
        }
        private global::System.String _SeriesID;
        partial void OnSeriesIDChanging(global::System.String value);
        partial void OnSeriesIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SeriesFull
        {
            get
            {
                return _SeriesFull;
            }
            set
            {
                OnSeriesFullChanging(value);
                ReportPropertyChanging("SeriesFull");
                _SeriesFull = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SeriesFull");
                OnSeriesFullChanged();
            }
        }
        private global::System.String _SeriesFull;
        partial void OnSeriesFullChanging(global::System.String value);
        partial void OnSeriesFullChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iBooxModel", "Books_Series", "Book")]
        public EntityCollection<Book> Books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Book>("iBooxModel.Books_Series", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Book>("iBooxModel.Books_Series", "Book", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="iBooxModel", Name="Tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="tagID">Initial value of the TagID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        public static Tag CreateTag(global::System.Int32 tagID, global::System.String title)
        {
            Tag tag = new Tag();
            tag.TagID = tagID;
            tag.Title = title;
            return tag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TagID
        {
            get
            {
                return _TagID;
            }
            set
            {
                if (_TagID != value)
                {
                    OnTagIDChanging(value);
                    ReportPropertyChanging("TagID");
                    _TagID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TagID");
                    OnTagIDChanged();
                }
            }
        }
        private global::System.Int32 _TagID;
        partial void OnTagIDChanging(global::System.Int32 value);
        partial void OnTagIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Count
        {
            get
            {
                return _Count;
            }
            set
            {
                OnCountChanging(value);
                ReportPropertyChanging("Count");
                _Count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count");
                OnCountChanged();
            }
        }
        private Nullable<global::System.Int32> _Count;
        partial void OnCountChanging(Nullable<global::System.Int32> value);
        partial void OnCountChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="iBooxModel", Name="Theme")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Theme : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Theme object.
        /// </summary>
        /// <param name="themeID">Initial value of the ThemeID property.</param>
        /// <param name="themeFull">Initial value of the ThemeFull property.</param>
        public static Theme CreateTheme(global::System.String themeID, global::System.String themeFull)
        {
            Theme theme = new Theme();
            theme.ThemeID = themeID;
            theme.ThemeFull = themeFull;
            return theme;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ThemeID
        {
            get
            {
                return _ThemeID;
            }
            set
            {
                if (_ThemeID != value)
                {
                    OnThemeIDChanging(value);
                    ReportPropertyChanging("ThemeID");
                    _ThemeID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ThemeID");
                    OnThemeIDChanged();
                }
            }
        }
        private global::System.String _ThemeID;
        partial void OnThemeIDChanging(global::System.String value);
        partial void OnThemeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ThemeFull
        {
            get
            {
                return _ThemeFull;
            }
            set
            {
                OnThemeFullChanging(value);
                ReportPropertyChanging("ThemeFull");
                _ThemeFull = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ThemeFull");
                OnThemeFullChanged();
            }
        }
        private global::System.String _ThemeFull;
        partial void OnThemeFullChanging(global::System.String value);
        partial void OnThemeFullChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iBooxModel", "Books_Themes", "Book")]
        public EntityCollection<Book> Books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Book>("iBooxModel.Books_Themes", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Book>("iBooxModel.Books_Themes", "Book", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
